spring:
  application:
    name: POS
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: com.mycompany.pos.CustomDialect
  datasource:
    url: jdbc:mysql://localhost:3306/java_pos?autoReconnect=true&useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver